name: AUXO
favicon: null
layout_spectrum: 0.45499541354365647
typography_spectrum: 0.22018357343040407
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#20062d'
    - '#fefefe'
    - '#00fe80'
    - '#fe0b53'
    - '#fea31f'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
